### ISSUE TITLE
Json Out put is blank of php array object. ?

### ISSUE THREAD

**Issue by harrypotter033** [bissolli/twitter-php-scraper#1]
```
<?php

require __DIR__ . '/../vendor/autoload.php';

$account = new \Bissolli\TwitterScraper\Twitter('twitter);

$account->loadTweets();

$pssarray = $account->getTweets();

$resultspss= json_encode($pssarray);

//Write Json to file
$fp = fopen('/home/ptest/public_html/boardapi/src/twitter/pull/resultspss.json', 'wa+');

fwrite($fp, $resultspss);
fclose($fp);

```
/* The output of the above code should be a .json file with JSON data of tweets but I am getting blank
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}], Please any recommendation what happen wrong here?*/

**Comment by bissolli** [comment]
You are using PHP 7.3, right?
I've just deployed the version v1.3 which adds support to this version!

Please, let me know if it's working now.

**Comment by bissolli** [comment]
Hey @hmpargi the model has all of its attrs protected, that is why you can encode to json.
I've just deployed a new version where will let you convert it to json, just update you package version to v1.3.1.
